### ISSUE TITLE
Use parallelly for better detection of available cores

### ISSUE THREAD

**Issue by izahn** [cole-brokamp/mappp#2]
I'm using DeGAUSS to geocode locally and a University HPC cluster. As is common in such an environment the machines have a large number of CPUs but I am limited to a subset of them. Unfortunately `parallel::detectCores()` has no support for this, and just returns the number of physical cores. This is bad because DeGAUSS ends up running 132 processes when I only have access to 4 cores!

The https://github.com/HenrikBengtsson/parallelly package offers an `availableCores()` function[1] that addresses this limitation. Would you be open to a PR swapping out the `parallel::detectCores` bit with `paralelly::availableCores`?

[1] https://github.com/HenrikBengtsson/parallelly/blob/develop/R/availableCores.R

**Comment by cole-brokamp** [comment]
I agree that this is a limitation and unexpected behavior.  I would definitely be open to a PR on this.  Thanks.

**Comment by cole-brokamp** [comment]
Thanks again.  Are you just using `degauss/geocoder` where this is a problem?  I want to make sure to update that one first.

**Comment by izahn** [comment]
Yes, I'm just using `degauss/geocoder` 3.0 from docker at the moment. (Actually I [converted the docker container to singularity](https://cloud.sylabs.io/library/izahn/default/degauss_geocoder) since docker isn't allowed on our HPC cluster, but I don't think that makes any difference.)

**Comment by cole-brokamp** [comment]
OK -- we will get this updated ASAP. 

The singularity conversion is very cool! We've been using some of the same workarounds and would want to incorporate into our official offerings.  We've had problems with some of the suggested methods to convert docker to singularity with the geocoder container, but haven't tried it lately.  Are there any specific methods you would be willing to share about how you did this?  I would love to set it up automatically for all of the DeGAUSS containers.

**Comment by izahn** [comment]
Awesome, thanks!

I didn't have to do much to convert to singularity. The repo for this work is unfortunately not publicly available (not my choice), but the `.def` file currently is

```
Bootstrap: docker
From: degauss/geocoder:latest
Stage: build

%post
    chmod -R ugo+Xr /root
    chmod -R ugo+Xr /opt
    chmod ugo+rx /root/geocoder/*
    export R_LIBS_USER=/root/geocoder/R

%runscript
    R_LIBS_USER=/root/geocoder/R /root/geocoder/geocode.R "$@"

%test
    echo "You should write some tests..."

%labels
    Author izahn@hbs.edu
    Version v0.1.0

%help
    DeGAUSS geocoder singularity image converted from https://hub.docker.com/r/degauss/geocoder/.
```
And then I have a wrapper `geocode.sh` like this:
```
#!/usr/bin/env bash

export SINGULARITY_BIND="/usr/local/app,/run,/export,$HOME,$PWD:/tmp"
singularity run ${GRID_EXP_ROOTDIR}/opt/singularity/degauss_3.0.sif "$@"
```

**Comment by cole-brokamp** [comment]
This is a fantastic resource for us, thank you so much!

**Comment by cole-brokamp** [comment]
Just to tie up our loose ends: Version 3.0.1 of the geocoder is out, which uses the updated version of mappp with the parallely support added.  Thank you again!

https://github.com/degauss-org/geocoder/releases/tag/v3.0.1

**Comment by izahn** [comment]
That is awesome, thank you!
