### ISSUE TITLE
Consider using furrr instead

### ISSUE THREAD

**Issue by izahn** [cole-brokamp/mappp#7]
https://github.com/DavisVaughan/furrr provides parallel map with progress. It is part of the *futureverse*, meaning that it can use a wide variety of parallel back-ends. My personal opinion (which may be worth nothing of course, you decide) is that it would be better to contribute any missing features to `furrr` rather than duplicate the effort.

**Comment by cole-brokamp** [comment]
Thanks for the note.  I have seen {furrr}, but I think my motivation here has to been to build something much more simple for a specific use case.  In my experience, {furrr} doesn't play well with pipes and was giving me problems with using nonstandard evaluation inside functions, and these are two things we often use in [DeGAUSS](https://degauss.org). 
That said, I do use {furrr} myself for some tasks, but would like to keep this as a _very_ simplified way to do parallel map with progress in this more controlled environment.
